# Generated by Django 3.0 on 2020-10-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='username',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
