# Generated by Django 3.1.6 on 2021-02-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201031_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='image',
            field=models.ImageField(blank=True, default='images/None/no-img.jpg', null=True, upload_to='images/'),
        ),
    ]
